version: '3'

services:
  apt-cacher-ng:
    restart: always
    image: ghcr.io/oct8l/apt-cacher-ng:latest
    init: true
    ports:
    - "3142:3142"
    volumes:
    - ${PWD}/apt-cacher-ng:/var/cache/apt-cacher-ng
